### ISSUE TITLE
Add ability to develop packages from subdirectory.

### ISSUE THREAD

**Issue by taras** [zerok/zerokspot.gitrecipe#2]
Use Case:
I have git repository that has src directory and all of the packages for this project are in that directory. I would like to be able to develop specific packages from that subdirectory.

Currently, this can not be done because the recipe assumes that the distutils file is in repository root.

Solution:
I added path option that allows the developer to indicate relative path of the package source files.
- Tests passed before and after the code modification.
- I tested this patch for my project and it worked
- I did not add tests because there was no test for develop and I didn't want to write one from scratch :) 

http://gist.github.com/208101

After the above patch, i replaced path for paths, so now you can develop multiple packages from the same git repo.

http://gist.github.com/208100

**Comment by zerok** [comment]
Thank you :-)

Your patches are in v0.5.0 with some additional unittests.

**Comment by taras** [comment]
Awesome,
I'll update my buildout.

Thank you,
taras
