### ISSUE TITLE
with statements incopatible with python2.5

### ISSUE THREAD

**Issue by attilaolah** [zerok/zerokspot.gitrecipe#3]
Hi,

I'd like to use this recipe with and appengine-based project, thus I'm using it in an environment where the default python is 2.5. Could you please add a "from **future** import with_statement" to the files that use the with statement? They do no harm in python2.6 anyway...

Thanks!

**Comment by zerok** [comment]
Grrr missed another file then. Will do it tonight or somewhen tomorrow morning. Sorry.

**Comment by attilaolah** [comment]
No problem; thanks for the quick response!

**Comment by zerok** [comment]
Closed by 3b18b79a2856b54bcb25f8a5e255016741f3fb17 (missing with-statement import in tests.py)
