### ISSUE TITLE
fatal: git checkout: --track and --no-track require -b

### ISSUE THREAD

**Issue by crucialfelix** [zerok/zerokspot.gitrecipe#5]
Hi, I'm checking out a non-master branch.  Fresh buildout, as simple as I can make it.  New to buildout, and git sometimes loses me, so its possible I'm missing something.

[buildout]
parts =
    nsgeo
develop = .

[nsgeo]
recipe = zerokspot.recipe.git
repository=ssh://111.22.33.444/home/crucial/gits/gitpo.git
branch=nsgeo

cruxnu:ns crucial$ ./bin/buildout
Develop: '/Users/crucial/Sites/buildouttest/ns/.'
Installing nsgeo.
remote: Counting objects: 22756, done.
remote: Compressing objects: 100% (15710/15710), done.
remote: Total 22756 (delta 13961), reused 12778 (delta 6345)
###### 

fatal: git checkout: --track and --no-track require -b
###### 

cd parts/nsgeo
git status
# On branch master

nothing to commit (working directory clean)
###### ########  didn't get the branch at all

cruxnu:nsgeo crucial$ git branch
- master

anyway, thanks so much for the gitrecipe !

**Comment by crucialfelix** [comment]
zerokspot/recipe/**init**.py
line 180:

```
        if self.branch != 'master':
            args = ('--track','-b', 'origin/%s' % self.branch, ) # adding -b
        else:
            args = ('master', )
```

cruxnu:nsgeo crucial$ git branch
  master
- origin/nsgeo

that checks it out correctly. but then running a second time still fails.

note that its no longer on the branch

cruxnu:ns crucial$ ./bin/buildout
Develop: '/Users/crucial/Sites/buildouttest/ns/.'
Updating nsgeo.
Pulling updates from origin
From ssh://111.22.33.444/home/crucial/gits/gitpo
- branch            nsgeo      -> FETCH_HEAD
  warning: too many files, skipping inexact rename detection
  CONFLICT (rename/delete): Renamed django/contrib/gis/db/backend/adaptor.py->django/contrib/gis/db/backends/adapter.py in HEAD and deleted in f9a91852384ac465b75f3635daae48498d26fc94
  CONFLICT CONFLICT CONFLICT etc.

**Comment by crucialfelix** [comment]
<pre>
diff --git a/zerokspot/recipe/git/__init__.py b/zerokspot/recipe/git/__init__.py
index 0d9ac37..5983097 100644
--- a/zerokspot/recipe/git/__init__.py
+++ b/zerokspot/recipe/git/__init__.py
@@ -30,7 +30,7 @@ def git(operation, args, message, ignore_errnos=None):
     exception with the given message. If ignore_errnos is a list of status
     codes, they will be not handled as errors if returned by git.
     """
-    real_args = ['-q'] + list(args)
+    real_args = list(args) # ['-q'] + 
     command = r'git %s ' + ' '.join(('"%s"', ) * len(real_args))
     command = command % ((operation, ) + tuple(real_args))
     status = subprocess.call(command, shell=True)
@@ -177,7 +177,8 @@ class Recipe(object):
             os.chdir(to)
 
             if self.branch != 'master':
-                args = ('-t', 'origin/%s' % self.branch, )
+                git('branch',('--track',self.branch,'origin/%s' % self.branch),"Failed to set up to track remote branch")
+                args = (self.branch,)
             else:
                 args = ('master', )
             git('checkout', args, "Failed to switch to branch '%s'" % args[-1],
</pre>


that does work. disregard previous, it did not really track the correct branch.
this does and is subsequent buildouts update correctly.

note that -q did not work for that command. does that break anything else to not use -q ? its just quiet.

**Comment by zerok** [comment]
Sorry for that, will look into it hopefully within the next 2 days (quite little free time right now :-( ).

**Comment by crucialfelix** [comment]
np, glad to help out.  sadly I'm still getting some issue, so my patch doesn't fix everything.  i'll look into it more today.

**Comment by zerok** [comment]
Just to be on the safe side: What version of git are you using?

**Comment by crucialfelix** [comment]
git 1.5.6.4

I have a new patch that has been performing nicely for several days.  and sadly, the only thing
I've been doing for the last two days is fiddling with buildout.  (other issues)

```
def _clone(self, from_, to):
    """
    Clone a repository located at ``from_`` to ``to``.
    """
    try:
        if not os.path.exists(to):
            git('clone', (from_, to), "Couldn't clone %s into %s" % (
                    from_, to, ))
        os.chdir(to)

        if self.branch != 'master':
            if not '[branch "%s"]' %self.branch in open('.git/CONFIG').read():
                git('branch',('--track',self.branch,'origin/%s' % self.branch),
                    "Failed to set up to track remote branch")
            if not "ref: refs/heads/%s" % self.branch in open('.git/HEAD').read():
                git('checkout', (self.branch,), "Failed to switch to branch '%s'" % self.branch,
                    ignore_errnos=[128])

        if self.rev is not None:
            git('checkout', (self.rev, ), "Failed to checkout revision")
    finally:
        os.chdir(self.root_dir)
```

this actually checks the state of the .git.   this way it recovers nicely if something went 
wrong on a previous install or update.  it tracks the branch only if it hasn't already, and
it switches to the branch only if it is not already there.

previously anytime there was an error the entire process would stop, leaving things in a broken state.
the only way I could restart was to clean the whole thing out and start over again.

**Comment by zerok** [comment]
Thank you :-) That version of git explains quite a bit :-)

I've already pushed your patch and disabled -q for the branch command. I hope this fixes this issue for your also within this repository ;-) 

If everything works I will build a new release hopefully on Monday.

**Comment by crucialfelix** [comment]
nope, I found a problem. let me chew over this for a bit and not bother you with noise. 

but briefly:

currently clone fails if the directory is already there.  I think, since its in parts, it should just delete and 
then clone.

```
def _clone(self, from_, to):
    """
    Clone a repository located at ``from_`` to ``to``.
    """
    try:
        if os.path.exists(to):
            # always get fresh
            print "removing ",to
            shutil.rmtree(to)

        git('clone', (from_, to), "Couldn't clone %s into %s" % (
                from_, to, ))
        os.chdir(to)

        if self.branch != 'master':
            if not '[branch "%s"]' %self.branch in open('.git/CONFIG').read():
                git('branch',('--track',self.branch,'origin/%s' % self.branch),
                    "Failed to set up to track remote branch")
            if not "ref: refs/heads/%s" % self.branch in open('.git/HEAD').read():
                git('checkout', (self.branch,), "Failed to switch to branch '%s'" % self.branch,
                    ignore_errnos=[128])

        if self.rev is not None:
            git('checkout', (self.rev, ), "Failed to checkout revision")
    finally:
        os.chdir(self.root_dir)
```

you can't depend on the folder that's there. I just got bit when I switched back and forth from 
install-from-cache.  the copy in parts has as its origin the copy that's in downloads. which is as it
should be.  it should be able to clone or update quickly from the cache copy.

I'm new to buildout, I guess if we use install-from-cache then we should do a pull for the cache copy ourselves
if we want new changes in.  that's the fastest way.

**Comment by crucialfelix** [comment]
closing (assuming you are going to do a pypi release soon)

**Comment by zerok** [comment]
Sorry for the delay with the release. I somehow forgot it back then and then noticed that Python development on Windows is a real pita.

**Comment by zerok** [comment]
Done. Thank you :-)
